### ISSUE TITLE
File upload resource definition crash

### ISSUE THREAD

**Issue by balazsnemeth** [MaximTovstashev/brest#5]
@MaximTovstashev  I defined my a resource on the following way, but `brest` does not accept it.

```
module.exports = {
  endpoints: [
    {
      method: 'post',
      /* validator: function (req) {
       req.assert('id').notEmpty();
       }, */
      description: 'Upload modeling CSV file',
      upload: function(multer) {
        return multer({
          dest: 'upload/'
        });
      }
    }
  ]
};
```

**Error**:
XXX/node_modules/express/lib/router/route.js:202
        throw new Error(msg);
        ^

Error: Route.post() requires a callback function but got a [object Object]
    at Route.(anonymous function) [as post] (/Users/nbalazs/Work/projects/presence/cfa-data-services/node_modules/express/lib/router/route.js:202:15)

**How should I defined a resource to accept multipart requests?**

**Comment by MaximTovstashev** [comment]
In this case 

```javascript
	  upload: {
	    	dest: 'uploads/'
	  }
```
should work just fine. The callback in upload description is needed, when you require access to multer object directly, for instance 

But I suspect that the application crashes because the handler function is missing. In your case it should be something like

```javascript
module.exports = {
  endpoints: [
    {
      method: 'post',
      /* validator: function (req) {
       req.assert('id').notEmpty();
       }, */
      description: 'Upload modeling CSV file',
      upload: {
          dest: 'upload/'
        },
      handler: function(req, callback) {
          doSomethingWithFile(req.file, req.body, callback);
      }
      }
    }
  ]
};
```

Also, please make sure that 'uploads/' directory is writable by the application. 

And, in any case, I will make adjustments to the library and documentation in order to make such situations more transparent. Thank you for your input!
